name: Deploy PWA to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'pwa/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload PWA
      uses: actions/upload-pages-artifact@v2
      with:
        path: './pwa'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

